# Generated by Django 3.2.8 on 2022-03-27 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0002_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='usersapp.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='repo',
            field=models.URLField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
