# Generated by Django 3.2.8 on 2022-03-27 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todo_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
